### ISSUE TITLE
<open-wc-demo> component does not load

### ISSUE THREAD

**Issue by snelson25** [open-wc/lit-demos#1]
Running on Windows 10 and Chrome Version 72.0.3626.109, main page is empty.   In Chrome dev tools,  index.js not being loaded into browser.   Added the following to index.html and main page was displayed: 

~~~~
  <script type="module">
    import './index.js';
  </script>

  <body>
    <open-wc-demo></open-wc-demo>
  </body>
</html>
~~~~

**Comment by thepassle** [comment]
The reason for this is that we're using stackblitz as a host for these demos, and stackblitz does some magic that'll load the index automagically. 

It's probably good to add it though, in case people clone this repo instead. Thanks for pointing this out :)

fixed in: https://github.com/open-wc/lit-demos/commit/54dfefa20f073cc0d7e818de5fa26e9240a4cb81
